# Generated by Django 6.0.1 on 2026-02-02 09:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('type_evenement', models.CharField(choices=[('rencontre', 'Rencontre'), ('ceremonie', 'Cérémonie'), ('conference', 'Conférence'), ('ziara', 'Ziara'), ('formation', 'Formation'), ('assemblee', 'Assemblée Générale'), ('autre', 'Autre')], max_length=50)),
                ('date_debut', models.DateTimeField()),
                ('date_fin', models.DateTimeField()),
                ('lieu', models.CharField(max_length=200)),
                ('adresse_complete', models.TextField(blank=True)),
                ('lien_visio', models.URLField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='evenements/')),
                ('capacite_max', models.IntegerField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('est_publie', models.BooleanField(default=False)),
                ('documents', models.FileField(blank=True, null=True, upload_to='evenements/docs/')),
                ('cree_par', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evenements_crees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Événement',
                'verbose_name_plural': 'Événements',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='GalerieMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('type_media', models.CharField(choices=[('image', 'Image'), ('video', 'Vidéo'), ('audio', 'Audio')], max_length=20)),
                ('fichier', models.FileField(upload_to='galerie/')),
                ('date_upload', models.DateTimeField(auto_now_add=True)),
                ('vues', models.IntegerField(default=0)),
                ('evenement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medias', to='informations.evenement')),
                ('upload_par', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Média',
                'verbose_name_plural': 'Galerie Médias',
                'ordering': ['-date_upload'],
            },
        ),
        migrations.CreateModel(
            name='Groupe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='groupes/')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('est_actif', models.BooleanField(default=True)),
                ('membres', models.ManyToManyField(blank=True, related_name='groupes_membre', to=settings.AUTH_USER_MODEL)),
                ('responsable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groupes_responsable', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Groupe',
                'verbose_name_plural': 'Groupes',
            },
        ),
        migrations.AddField(
            model_name='evenement',
            name='groupes_cibles',
            field=models.ManyToManyField(blank=True, to='informations.groupe'),
        ),
        migrations.CreateModel(
            name='Annonce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('contenu', models.TextField()),
                ('priorite', models.CharField(choices=[('normale', 'Normale'), ('importante', 'Importante'), ('urgente', 'Urgente')], default='normale', max_length=20)),
                ('date_publication', models.DateTimeField(auto_now_add=True)),
                ('date_expiration', models.DateTimeField(blank=True, null=True)),
                ('est_active', models.BooleanField(default=True)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('groupes_cibles', models.ManyToManyField(blank=True, to='informations.groupe')),
            ],
            options={
                'verbose_name': 'Annonce',
                'verbose_name_plural': 'Annonces',
                'ordering': ['-date_publication'],
            },
        ),
        migrations.CreateModel(
            name='ParticipationEvenement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('est_present', models.BooleanField(default=False)),
                ('commentaire', models.TextField(blank=True)),
                ('evenement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='informations.evenement')),
                ('membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Participation Événement',
                'verbose_name_plural': 'Participations Événements',
                'unique_together': {('evenement', 'membre')},
            },
        ),
        migrations.AddField(
            model_name='evenement',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='inscriptions_evenements', through='informations.ParticipationEvenement', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('contenu', models.TextField()),
                ('categorie', models.CharField(choices=[('article', 'Article'), ('enseignement', 'Enseignement'), ('newsletter', 'Newsletter'), ('communique', 'Communiqué'), ('blog', 'Blog')], max_length=50)),
                ('image_principale', models.ImageField(blank=True, null=True, upload_to='publications/')),
                ('date_publication', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('est_publiee', models.BooleanField(default=False)),
                ('vues', models.IntegerField(default=0)),
                ('tags', models.CharField(blank=True, max_length=200)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Publication',
                'verbose_name_plural': 'Publications',
                'ordering': ['-date_publication'],
            },
        ),
    ]
