# Generated by Django 4.2.29 on 2026-08-23 19:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("informations", "0003_alter_newspost_titre_contenu"),
    ]

    operations = [
        migrations.AddField(
            model_name="newsimage",
            name="type_media",
            field=models.CharField(
                choices=[("image", "Image"), ("video", "Vidéo")],
                default="image",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="newsimage",
            name="image",
            field=models.FileField(upload_to="news/"),
        ),
        migrations.CreateModel(
            name="EvenementComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("texte", models.TextField()),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                (
                    "evenement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="informations.evenement",
                    ),
                ),
                (
                    "membre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evenement_comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="informations.evenementcomment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Commentaire (événement)",
                "verbose_name_plural": "Commentaires (événement)",
                "ordering": ["date_creation"],
            },
        ),
        migrations.CreateModel(
            name="EvenementLike",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                (
                    "evenement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="likes",
                        to="informations.evenement",
                    ),
                ),
                (
                    "membre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evenement_likes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Like (événement)",
                "verbose_name_plural": "Likes (événement)",
                "unique_together": {("evenement", "membre")},
            },
        ),
    ]
