# Generated by Django 6.0.1 on 2026-02-02 09:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieForum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icone', models.CharField(blank=True, max_length=50)),
                ('ordre', models.IntegerField(default=0)),
                ('est_active', models.BooleanField(default=True)),
                ('moderateurs', models.ManyToManyField(blank=True, related_name='categories_moderees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Catégorie de Forum',
                'verbose_name_plural': 'Catégories de Forum',
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sujet', models.CharField(max_length=200)),
                ('contenu', models.TextField()),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('est_lu', models.BooleanField(default=False)),
                ('date_lecture', models.DateTimeField(blank=True, null=True)),
                ('est_archive_expediteur', models.BooleanField(default=False)),
                ('est_archive_destinataire', models.BooleanField(default=False)),
                ('fichier_joint', models.FileField(blank=True, null=True, upload_to='messages/pieces_jointes/')),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_recus', to=settings.AUTH_USER_MODEL)),
                ('expediteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_envoyes', to=settings.AUTH_USER_MODEL)),
                ('message_parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reponses', to='communication.message')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'ordering': ['-date_envoi'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_notification', models.CharField(choices=[('info', 'Information'), ('succes', 'Succès'), ('avertissement', 'Avertissement'), ('erreur', 'Erreur'), ('message', 'Message'), ('evenement', 'Événement'), ('finance', 'Finance'), ('kamil', 'Kamil'), ('systeme', 'Système')], max_length=20)),
                ('titre', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('lien', models.CharField(blank=True, max_length=200)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('est_lue', models.BooleanField(default=False)),
                ('date_lecture', models.DateTimeField(blank=True, null=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='SujetForum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('contenu', models.TextField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('est_epingle', models.BooleanField(default=False)),
                ('est_verrouille', models.BooleanField(default=False)),
                ('vues', models.IntegerField(default=0)),
                ('tags', models.CharField(blank=True, max_length=200)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sujets_forum', to=settings.AUTH_USER_MODEL)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sujets', to='communication.categorieforum')),
            ],
            options={
                'verbose_name': 'Sujet de Forum',
                'verbose_name_plural': 'Sujets de Forum',
                'ordering': ['-est_epingle', '-date_modification'],
            },
        ),
        migrations.CreateModel(
            name='ReponseForum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('est_modere', models.BooleanField(default=False)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponses_forum', to=settings.AUTH_USER_MODEL)),
                ('reponse_parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sous_reponses', to='communication.reponseforum')),
                ('sujet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponses', to='communication.sujetforum')),
            ],
            options={
                'verbose_name': 'Réponse de Forum',
                'verbose_name_plural': 'Réponses de Forum',
                'ordering': ['date_creation'],
            },
        ),
    ]
