# Generated by Django 6.0.1 on 2026-08-22 15:07

import apps.communication.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("communication", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Canal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="communication/canaux/images/"
                    ),
                ),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("est_actif", models.BooleanField(default=True)),
                (
                    "lien_reunion",
                    models.URLField(
                        blank=True,
                        help_text="Lien Jitsi de la réunion en cours, le cas échéant",
                    ),
                ),
                (
                    "cree_par",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="canaux_crees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Canal de discussion",
                "verbose_name_plural": "Canaux de discussion",
                "ordering": ["-date_creation"],
            },
        ),
        migrations.CreateModel(
            name="MessageCanal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_message",
                    models.CharField(
                        choices=[
                            ("texte", "Texte"),
                            ("image", "Image"),
                            ("document", "Document"),
                            ("audio", "Audio"),
                            ("video", "Vidéo"),
                        ],
                        default="texte",
                        max_length=20,
                    ),
                ),
                ("contenu", models.TextField(blank=True)),
                (
                    "fichier",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=apps.communication.models.chemin_fichier_canal,
                    ),
                ),
                (
                    "duree",
                    models.IntegerField(
                        blank=True,
                        help_text="Durée en secondes (audio/vidéo)",
                        null=True,
                    ),
                ),
                ("date_envoi", models.DateTimeField(auto_now_add=True)),
                (
                    "canal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="communication.canal",
                    ),
                ),
                (
                    "expediteur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages_canaux",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "repond_a",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reponses",
                        to="communication.messagecanal",
                    ),
                ),
            ],
            options={
                "verbose_name": "Message de Canal",
                "verbose_name_plural": "Messages de Canaux",
                "ordering": ["date_envoi"],
            },
        ),
        migrations.CreateModel(
            name="MembreCanal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("est_admin_canal", models.BooleanField(default=False)),
                ("date_ajout", models.DateTimeField(auto_now_add=True)),
                (
                    "canal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="membres_canal",
                        to="communication.canal",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="canaux",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Membre de Canal",
                "verbose_name_plural": "Membres de Canaux",
                "unique_together": {("canal", "user")},
            },
        ),
    ]
