# Generated by Django 4.2.30 on 2026-08-22 23:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("communication", "0002_canal_messagecanal_membrecanal"),
    ]

    operations = [
        migrations.CreateModel(
            name="AbonnementPush",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("endpoint", models.URLField(max_length=500, unique=True)),
                ("cle_p256dh", models.CharField(max_length=200)),
                ("cle_auth", models.CharField(max_length=100)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="abonnements_push",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Abonnement Push",
                "verbose_name_plural": "Abonnements Push",
            },
        ),
    ]
