# Generated by Django 4.2.30 on 2026-08-23 10:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("communication", "0003_abonnementpush"),
    ]

    operations = [
        migrations.AddField(
            model_name="messagecanal",
            name="masque_pour",
            field=models.ManyToManyField(
                blank=True,
                help_text="Membres ayant supprimé ce message de leur côté uniquement (le message reste visible pour les autres)",
                related_name="messages_canaux_masques",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
