# Generated by Django 4.2.30 on 2026-09-15 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("communication", "0004_messagecanal_masque_pour"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="type_notification",
            field=models.CharField(
                choices=[
                    ("info", "Information"),
                    ("succes", "Succès"),
                    ("avertissement", "Avertissement"),
                    ("erreur", "Erreur"),
                    ("message", "Message"),
                    ("evenement", "Événement"),
                    ("finance", "Finance"),
                    ("kamil", "Kamil"),
                    ("majaaliss", "Majaaliss"),
                    ("laaj", "LAAJ"),
                    ("systeme", "Système"),
                ],
                max_length=20,
            ),
        ),
    ]
