# Generated by Django 4.2.30 on 2026-10-01 00:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="IncidentSysteme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("backend", "Serveur (backend)"),
                            ("web", "Site web"),
                            ("mobile", "Application mobile"),
                            ("surveillance", "Surveillance"),
                        ],
                        default="backend",
                        max_length=20,
                    ),
                ),
                (
                    "niveau",
                    models.CharField(
                        choices=[
                            ("critique", "Critique"),
                            ("erreur", "Erreur"),
                            ("avertissement", "Avertissement"),
                        ],
                        default="erreur",
                        max_length=20,
                    ),
                ),
                ("titre", models.CharField(max_length=255)),
                (
                    "details",
                    models.TextField(
                        blank=True,
                        help_text="Trace complète (traceback) de la dernière occurrence",
                    ),
                ),
                ("chemin", models.CharField(blank=True, max_length=255)),
                ("methode", models.CharField(blank=True, max_length=10)),
                (
                    "statut_http",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("request_id", models.CharField(blank=True, max_length=40)),
                ("user_agent", models.CharField(blank=True, max_length=300)),
                ("signature", models.CharField(db_index=True, max_length=64)),
                ("occurrences", models.PositiveIntegerField(default=1)),
                ("premiere_date", models.DateTimeField(auto_now_add=True)),
                ("derniere_date", models.DateTimeField(auto_now=True)),
                ("dernier_email", models.DateTimeField(blank=True, null=True)),
                ("resolu", models.BooleanField(db_index=True, default=False)),
                (
                    "utilisateur",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="incidents_systeme",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Incident technique",
                "verbose_name_plural": "Incidents techniques",
                "ordering": ["-derniere_date"],
            },
        ),
    ]
