# Generated by Django 6.0.1 on 2026-02-02 09:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DomaineScientifique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icone', models.CharField(blank=True, max_length=50)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sous_domaines', to='scientifique.domainescientifique')),
            ],
            options={
                'verbose_name': 'Domaine Scientifique',
                'verbose_name_plural': 'Domaines Scientifiques',
            },
        ),
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField()),
                ('objectifs', models.TextField()),
                ('niveau', models.CharField(choices=[('debutant', 'Débutant'), ('intermediaire', 'Intermédiaire'), ('avance', 'Avancé'), ('expert', 'Expert')], max_length=20)),
                ('duree', models.IntegerField(help_text='Durée en heures')),
                ('prerequis', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='scientifique/cours/')),
                ('video_presentation', models.FileField(blank=True, null=True, upload_to='scientifique/cours/videos/')),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('publie', 'Publié'), ('archive', 'Archivé')], default='brouillon', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_publication', models.DateTimeField(blank=True, null=True)),
                ('capacite_max', models.IntegerField(blank=True, null=True)),
                ('prix', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('est_gratuit', models.BooleanField(default=True)),
                ('formateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cours_enseignes', to=settings.AUTH_USER_MODEL)),
                ('domaine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scientifique.domainescientifique')),
            ],
            options={
                'verbose_name': 'Cours',
                'verbose_name_plural': 'Cours',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='InscriptionCours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('date_debut', models.DateField(blank=True, null=True)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('inscrit', 'Inscrit'), ('en_cours', 'En cours'), ('termine', 'Terminé'), ('abandonne', 'Abandonné')], default='inscrit', max_length=20)),
                ('progression', models.IntegerField(default=0, help_text='Pourcentage de complétion')),
                ('note_finale', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('certificat', models.FileField(blank=True, null=True, upload_to='scientifique/certificats/')),
                ('apprenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scientifique.cours')),
            ],
            options={
                'verbose_name': 'Inscription Cours',
                'verbose_name_plural': 'Inscriptions Cours',
                'unique_together': {('cours', 'apprenant')},
            },
        ),
        migrations.AddField(
            model_name='cours',
            name='inscrits',
            field=models.ManyToManyField(blank=True, related_name='cours_suivis', through='scientifique.InscriptionCours', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ModuleCours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('duree', models.IntegerField(help_text='Durée en heures')),
                ('ordre', models.IntegerField(default=0)),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='scientifique.cours')),
            ],
            options={
                'verbose_name': 'Module de Cours',
                'verbose_name_plural': 'Modules de Cours',
                'ordering': ['cours', 'ordre'],
                'unique_together': {('cours', 'numero')},
            },
        ),
        migrations.CreateModel(
            name='OuvrageScientifique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('auteur', models.CharField(max_length=200)),
                ('resume', models.TextField()),
                ('fichier', models.FileField(upload_to='scientifique/ouvrages/')),
                ('couverture', models.ImageField(blank=True, null=True, upload_to='scientifique/couvertures/')),
                ('annee_publication', models.IntegerField()),
                ('editeur', models.CharField(blank=True, max_length=200)),
                ('isbn', models.CharField(blank=True, max_length=50)),
                ('nombre_pages', models.IntegerField(blank=True, null=True)),
                ('langue', models.CharField(default='Français', max_length=50)),
                ('mots_cles', models.CharField(blank=True, max_length=200)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('telechargements', models.IntegerField(default=0)),
                ('ajoute_par', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('domaine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scientifique.domainescientifique')),
            ],
            options={
                'verbose_name': 'Ouvrage Scientifique',
                'verbose_name_plural': 'Ouvrages Scientifiques',
                'ordering': ['-date_ajout'],
            },
        ),
        migrations.CreateModel(
            name='PublicationScientifique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('type_publication', models.CharField(choices=[('article', 'Article'), ('these', 'Thèse'), ('memoire', 'Mémoire'), ('communication', 'Communication'), ('poster', 'Poster')], max_length=50)),
                ('auteurs', models.TextField(help_text='Liste des auteurs')),
                ('resume', models.TextField()),
                ('revue', models.CharField(blank=True, max_length=200)),
                ('conference', models.CharField(blank=True, max_length=200)),
                ('annee', models.IntegerField()),
                ('doi', models.CharField(blank=True, max_length=100)),
                ('fichier', models.FileField(upload_to='scientifique/publications/')),
                ('mots_cles', models.CharField(max_length=200)),
                ('date_soumission', models.DateTimeField(auto_now_add=True)),
                ('vues', models.IntegerField(default=0)),
                ('citations', models.IntegerField(default=0)),
                ('domaine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scientifique.domainescientifique')),
                ('soumis_par', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Publication Scientifique',
                'verbose_name_plural': 'Publications Scientifiques',
                'ordering': ['-annee'],
            },
        ),
        migrations.CreateModel(
            name='LeconCours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('titre', models.CharField(max_length=200)),
                ('contenu_texte', models.TextField(blank=True)),
                ('contenu_video', models.FileField(blank=True, null=True, upload_to='scientifique/lecons/videos/')),
                ('contenu_pdf', models.FileField(blank=True, null=True, upload_to='scientifique/lecons/pdf/')),
                ('duree', models.IntegerField(help_text='Durée en minutes')),
                ('ordre', models.IntegerField(default=0)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecons', to='scientifique.modulecours')),
            ],
            options={
                'verbose_name': 'Leçon',
                'verbose_name_plural': 'Leçons',
                'ordering': ['module', 'ordre'],
                'unique_together': {('module', 'numero')},
            },
        ),
    ]
