# Generated by Django 6.0.1 on 2026-02-02 09:40

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParametresFinanciers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_cotisation_defaut', models.DecimalField(decimal_places=2, default=Decimal('1000.00'), max_digits=10)),
                ('jour_echeance_cotisation', models.IntegerField(default=5)),
                ('delai_relance_jours', models.IntegerField(default=7)),
                ('email_notification_paiement', models.BooleanField(default=True)),
                ('sms_notification_paiement', models.BooleanField(default=False)),
                ('wave_api_key', models.CharField(blank=True, max_length=200)),
                ('wave_secret_key', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'Paramètres Financiers',
                'verbose_name_plural': 'Paramètres Financiers',
            },
        ),
        migrations.CreateModel(
            name='CotisationMensuelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, default=Decimal('1000.00'), max_digits=10)),
                ('mois', models.IntegerField()),
                ('annee', models.IntegerField()),
                ('date_echeance', models.DateField()),
                ('date_paiement', models.DateTimeField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('payee', 'Payée'), ('retard', 'En retard'), ('annulee', 'Annulée')], default='en_attente', max_length=20)),
                ('reference_wave', models.CharField(blank=True, max_length=100)),
                ('mode_paiement', models.CharField(default='wave', max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotisations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cotisation Mensuelle',
                'verbose_name_plural': 'Cotisations Mensuelles',
                'ordering': ['-annee', '-mois'],
                'unique_together': {('membre', 'mois', 'annee')},
            },
        ),
        migrations.CreateModel(
            name='LeveeFonds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('objectif', models.TextField()),
                ('montant_objectif', models.DecimalField(decimal_places=2, max_digits=12)),
                ('montant_collecte', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('montant_par_membre', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='levees_fonds/')),
                ('lien_paiement_wave', models.URLField(blank=True)),
                ('statut', models.CharField(choices=[('active', 'Active'), ('terminee', 'Terminée'), ('annulee', 'Annulée')], default='active', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('cree_par', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Levée de Fonds',
                'verbose_name_plural': 'Levées de Fonds',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_transaction', models.CharField(choices=[('cotisation', 'Cotisation Mensuelle'), ('levee_fonds', 'Levée de Fonds'), ('don', 'Don'), ('depense', 'Dépense'), ('autre', 'Autre')], max_length=50)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True)),
                ('date_transaction', models.DateTimeField(auto_now_add=True)),
                ('reference_wave', models.CharField(blank=True, max_length=100)),
                ('reference_interne', models.CharField(max_length=100, unique=True)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('validee', 'Validée'), ('echouee', 'Échouée'), ('remboursee', 'Remboursée')], default='en_attente', max_length=20)),
                ('recu_genere', models.BooleanField(default=False)),
                ('fichier_recu', models.FileField(blank=True, null=True, upload_to='recus/')),
                ('cotisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.cotisationmensuelle')),
                ('levee_fonds', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.leveefonds')),
                ('membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-date_transaction'],
            },
        ),
        migrations.CreateModel(
            name='Don',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('message', models.TextField(blank=True)),
                ('est_anonyme', models.BooleanField(default=False)),
                ('date_don', models.DateTimeField(auto_now_add=True)),
                ('reference_wave', models.CharField(blank=True, max_length=100)),
                ('donateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dons', to=settings.AUTH_USER_MODEL)),
                ('transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='finance.transaction')),
            ],
            options={
                'verbose_name': 'Don',
                'verbose_name_plural': 'Dons',
                'ordering': ['-date_don'],
            },
        ),
    ]
