# Generated by Django 6.0.1 on 2026-02-03 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotisationmensuelle',
            name='objet_assignation',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='cotisationmensuelle',
            name='type_cotisation',
            field=models.CharField(choices=[('mensualite', 'Mensualité'), ('assignation', 'Assignation')], default='mensualite', max_length=20),
        ),
    ]
