# Generated by Django 6.0.1 on 2026-02-03 10:07

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_cotisationmensuelle_objet_assignation_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cotisationmensuelle',
            unique_together={('membre', 'mois', 'annee', 'type_cotisation')},
        ),
    ]
