# Generated by Django 4.2.30 on 2026-08-23 00:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("finance", "0004_cotisation_unique_with_objet"),
    ]

    operations = [
        migrations.CreateModel(
            name="Depense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("motif", models.CharField(max_length=200)),
                (
                    "categorie",
                    models.CharField(
                        choices=[
                            ("MAGAL", "Magal"),
                            ("GAMOU", "Gamou"),
                            ("KAZU RAJABB", "Kazu Rajabb"),
                            ("KOOR", "Koor"),
                            ("SOCIAL", "Social"),
                            ("XELCOM", "Xelcom"),
                            ("MENSUALITE", "Mensualités"),
                            ("AUTRES", "Autres"),
                        ],
                        default="AUTRES",
                        max_length=30,
                    ),
                ),
                ("montant", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "justificatif",
                    models.FileField(
                        blank=True, null=True, upload_to="finance/depenses/"
                    ),
                ),
                ("date_depense", models.DateField()),
                ("date_validation", models.DateTimeField(blank=True, null=True)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("en_attente", "En attente"),
                            ("validee", "Validée"),
                            ("refusee", "Refusée"),
                        ],
                        default="en_attente",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                (
                    "cree_par",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="depenses_creees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "valide_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="depenses_validees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Dépense",
                "verbose_name_plural": "Dépenses",
                "ordering": ["-date_depense"],
            },
        ),
    ]
