# Generated by Django 4.2.30 on 2026-08-23 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0005_depense"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cotisationmensuelle",
            name="objet_assignation",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
    ]
