# Generated by Django 4.2.29 on 2026-08-23 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0006_alter_cotisationmensuelle_objet_assignation"),
    ]

    operations = [
        migrations.AddField(
            model_name="cotisationmensuelle",
            name="date_declaration",
            field=models.DateTimeField(
                blank=True,
                help_text="Date à laquelle le membre a déclaré son paiement, avant confirmation par le chargé de finance",
                null=True,
            ),
        ),
    ]
