# Generated by Django 4.2.29 on 2026-08-23 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0007_cotisationmensuelle_date_declaration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cotisationmensuelle",
            name="statut",
            field=models.CharField(
                choices=[
                    ("en_attente", "En attente"),
                    ("declare", "Déclaré"),
                    ("payee", "Payée"),
                    ("retard", "En retard"),
                    ("annulee", "Annulée"),
                ],
                default="en_attente",
                max_length=20,
            ),
        ),
    ]
