# Generated by Django 6.0.1 on 2026-02-02 09:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiviteReligieuse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('type_activite', models.CharField(choices=[('wird', 'Wird'), ('khassida', 'Khassida'), ('tafsir', 'Tafsir'), ('cours', 'Cours religieux'), ('sermon', 'Sermon'), ('conference', 'Conférence'), ('autre', 'Autre')], max_length=50)),
                ('description', models.TextField()),
                ('date_activite', models.DateTimeField()),
                ('duree', models.IntegerField(help_text='Durée en minutes')),
                ('lieu', models.CharField(max_length=200)),
                ('lien_visio', models.URLField(blank=True)),
                ('capacite_max', models.IntegerField(blank=True, null=True)),
                ('supports', models.FileField(blank=True, null=True, upload_to='activites/supports/')),
                ('enregistrement', models.FileField(blank=True, null=True, upload_to='activites/enregistrements/')),
                ('animateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activites_animees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Activité Religieuse',
                'verbose_name_plural': 'Activités Religieuses',
                'ordering': ['-date_activite'],
            },
        ),
        migrations.CreateModel(
            name='Enseignement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('categorie', models.CharField(choices=[('coran', 'Coran et Tafsir'), ('hadith', 'Hadith'), ('fiqh', 'Fiqh (Jurisprudence)'), ('aqida', 'Aqida (Croyance)'), ('sira', 'Sira (Vie du Prophète)'), ('akhlaq', 'Akhlaq (Morale)'), ('khassaida', 'Khassaïd'), ('autre', 'Autre')], max_length=50)),
                ('contenu', models.TextField()),
                ('fichier_audio', models.FileField(blank=True, null=True, upload_to='enseignements/audio/')),
                ('fichier_video', models.FileField(blank=True, null=True, upload_to='enseignements/video/')),
                ('fichier_pdf', models.FileField(blank=True, null=True, upload_to='enseignements/pdf/')),
                ('date_publication', models.DateTimeField(auto_now_add=True)),
                ('vues', models.IntegerField(default=0)),
                ('tags', models.CharField(blank=True, max_length=200)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enseignements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Enseignement',
                'verbose_name_plural': 'Enseignements',
                'ordering': ['-date_publication'],
            },
        ),
        migrations.CreateModel(
            name='Kamil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('objectifs', models.TextField(blank=True)),
                ('nombre_chapitres', models.IntegerField(default=30)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='kamil/')),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('termine', 'Terminé'), ('archive', 'Archivé')], default='actif', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('cree_par', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Programme Kamil',
                'verbose_name_plural': 'Programmes Kamil',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Chapitre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('titre', models.CharField(max_length=200)),
                ('sous_titre', models.CharField(blank=True, max_length=200)),
                ('contenu_texte', models.TextField(blank=True)),
                ('contenu_audio', models.FileField(blank=True, null=True, upload_to='chapitres/audio/')),
                ('contenu_video', models.FileField(blank=True, null=True, upload_to='chapitres/video/')),
                ('duree_lecture_estimee', models.IntegerField(blank=True, help_text='Durée en minutes', null=True)),
                ('references', models.TextField(blank=True)),
                ('notes_pedagogiques', models.TextField(blank=True)),
                ('est_publie', models.BooleanField(default=True)),
                ('kamil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapitres', to='culturelle.kamil')),
            ],
            options={
                'verbose_name': 'Chapitre',
                'verbose_name_plural': 'Chapitres',
                'ordering': ['kamil', 'numero'],
                'unique_together': {('kamil', 'numero')},
            },
        ),
        migrations.CreateModel(
            name='ParticipationActivite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('a_participe', models.BooleanField(default=False)),
                ('evaluation', models.IntegerField(blank=True, null=True)),
                ('commentaire', models.TextField(blank=True)),
                ('certificat_genere', models.BooleanField(default=False)),
                ('activite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='culturelle.activitereligieuse')),
                ('membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Participation Activité',
                'verbose_name_plural': 'Participations Activités',
                'unique_together': {('membre', 'activite')},
            },
        ),
        migrations.CreateModel(
            name='ProgressionLecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('non_lu', 'Non lu'), ('en_cours', 'En cours'), ('lu', 'Lu - En attente validation'), ('valide', 'Validé'), ('refuse', 'Refusé')], default='non_lu', max_length=30)),
                ('date_lecture', models.DateField(blank=True, null=True)),
                ('temps_lecture', models.IntegerField(blank=True, help_text='Temps en minutes', null=True)),
                ('notes_membre', models.TextField(blank=True)),
                ('est_valide', models.BooleanField(default=False)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('commentaire_validation', models.TextField(blank=True)),
                ('note_comprehension', models.IntegerField(blank=True, null=True)),
                ('chapitre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='culturelle.chapitre')),
                ('kamil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='culturelle.kamil')),
                ('membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progressions_kamil', to=settings.AUTH_USER_MODEL)),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validations_effectuees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Progression de Lecture',
                'verbose_name_plural': 'Progressions de Lecture',
                'ordering': ['membre', 'kamil', 'chapitre__numero'],
                'unique_together': {('membre', 'kamil', 'chapitre')},
            },
        ),
    ]
