# Generated by Django 6.0.1 on 2026-02-02 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culturelle', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kamil',
            name='annee',
            field=models.IntegerField(default=2024, help_text='Année scolaire / civile'),
        ),
        migrations.AddField(
            model_name='kamil',
            name='semestre',
            field=models.IntegerField(choices=[(1, 'Semestre 1'), (2, 'Semestre 2')], default=1),
        ),
        migrations.AlterField(
            model_name='kamil',
            name='nombre_chapitres',
            field=models.IntegerField(default=30, help_text='Nombre de juzz (30 pour le Coran)'),
        ),
    ]
