# Generated by Django 6.0.1 on 2026-02-02 22:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culturelle', '0002_kamil_semestre_annee'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='progressionlecture',
            name='montant_assigne',
            field=models.DecimalField(decimal_places=0, default=0, help_text='Montant à payer pour ce juzz (en FCFA)', max_digits=10),
        ),
        migrations.AddField(
            model_name='progressionlecture',
            name='montant_verse',
            field=models.DecimalField(decimal_places=0, default=0, help_text='Montant total versé', max_digits=10),
        ),
        migrations.CreateModel(
            name='VersementKamil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=0, help_text='Montant versé (en FCFA)', max_digits=10)),
                ('methode_paiement', models.CharField(choices=[('wave', 'Wave'), ('om', 'Orange Money'), ('espece', 'Espèces'), ('virement', 'Virement bancaire'), ('autre', 'Autre')], default='wave', max_length=20)),
                ('numero_transaction', models.CharField(blank=True, help_text='Numéro de transaction Wave/OM', max_length=100)),
                ('date_versement', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente de validation'), ('valide', 'Validé'), ('refuse', 'Refusé')], default='en_attente', max_length=20)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('commentaire', models.TextField(blank=True)),
                ('membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versements_kamil', to=settings.AUTH_USER_MODEL)),
                ('progression', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versements', to='culturelle.progressionlecture')),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versements_valides', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Versement Kamil',
                'verbose_name_plural': 'Versements Kamil',
                'ordering': ['-date_versement'],
            },
        ),
    ]
