# Generated by Django

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def create_jukkis_for_existing_kamils(apps, schema_editor):
    Kamil = apps.get_model('culturelle', 'Kamil')
    Jukki = apps.get_model('culturelle', 'Jukki')
    for kamil in Kamil.objects.all():
        for numero in range(1, 31):
            Jukki.objects.get_or_create(kamil=kamil, numero=numero)


class Migration(migrations.Migration):

    dependencies = [
        ('culturelle', '0003_add_versements_kamil'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Jukki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(help_text='1 à 30')),
                ('est_valide', models.BooleanField(default=False)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('kamil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jukkis', to='culturelle.kamil')),
                ('membre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jukkis_assignes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'JUKKI',
                'verbose_name_plural': 'JUKKIs',
                'ordering': ['kamil', 'numero'],
                'unique_together': {('kamil', 'numero')},
            },
        ),
        migrations.RunPython(create_jukkis_for_existing_kamils),
    ]
