# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culturelle', '0004_jukki'),
    ]

    operations = [
        migrations.AddField(
            model_name='kamil',
            name='nb_lectures',
            field=models.IntegerField(default=0, help_text='Nombre de cycles/kamil lus (incrémenté à chaque Recommencer)'),
        ),
    ]
