# Generated by Django 4.2.30 on 2026-09-15 15:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("culturelle", "0005_add_kamil_nb_lectures"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssignationTere",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom_tere",
                    models.CharField(
                        help_text="Nom du TERE (livre) : KUN KAATIMAN, TAZA WUDU SIXAAR, JAWXARATUN NAFIIS, NAXJU, ou un autre.",
                        max_length=200,
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[("en_cours", "En cours"), ("termine", "Terminé")],
                        default="en_cours",
                        max_length=20,
                    ),
                ),
                ("date_assignation", models.DateTimeField(auto_now_add=True)),
                ("date_fin", models.DateTimeField(blank=True, null=True)),
                (
                    "assigne_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tere_assignes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "membre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignations_tere",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Assignation TERE (Majaaliss)",
                "verbose_name_plural": "Assignations TERE (Majaaliss)",
                "ordering": ["membre", "-date_assignation"],
            },
        ),
        migrations.CreateModel(
            name="Laaj",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.TextField()),
                ("date_question", models.DateTimeField(auto_now_add=True)),
                ("reponse", models.TextField(blank=True)),
                ("date_reponse", models.DateTimeField(blank=True, null=True)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("en_attente", "En attente de réponse"),
                            ("repondu", "Répondu"),
                        ],
                        default="en_attente",
                        max_length=20,
                    ),
                ),
                (
                    "membre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="laaj_questions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "repondu_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="laaj_reponses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "LAAJ (question religieuse)",
                "verbose_name_plural": "LAAJ (questions religieuses)",
                "ordering": ["-date_question"],
            },
        ),
        migrations.CreateModel(
            name="Bind",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero",
                    models.PositiveIntegerField(
                        help_text="BIND 1, BIND 2, ... — attribué automatiquement à la création"
                    ),
                ),
                (
                    "page",
                    models.CharField(
                        blank=True,
                        help_text="Page(s) du TERE couverte(s) par ce BIND",
                        max_length=50,
                    ),
                ),
                (
                    "audio",
                    models.FileField(
                        help_text="Vocal du jewrine culturelle (transcription)",
                        upload_to="majaaliss/binds/audio/",
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                (
                    "assignation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="binds",
                        to="culturelle.assignationtere",
                    ),
                ),
                (
                    "cree_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="binds_crees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "BIND",
                "verbose_name_plural": "BINDs",
                "ordering": ["assignation", "numero"],
                "unique_together": {("assignation", "numero")},
            },
        ),
    ]
