# Generated by Django 4.2.30 on 2026-09-15 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("culturelle", "0006_assignationtere_laaj_bind"),
    ]

    operations = [
        migrations.AddField(
            model_name="laaj",
            name="question_audio",
            field=models.FileField(
                blank=True, null=True, upload_to="laaj/questions/audio/"
            ),
        ),
        migrations.AddField(
            model_name="laaj",
            name="reponse_audio",
            field=models.FileField(
                blank=True, null=True, upload_to="laaj/reponses/audio/"
            ),
        ),
        migrations.AlterField(
            model_name="laaj",
            name="question",
            field=models.TextField(blank=True),
        ),
    ]
