# Generated by Django 4.2.30 on 2026-09-15 15:48

from django.db import migrations, models


def nettoyer_pages_non_numeriques(apps, schema_editor):
    """Avant de passer `page` en entier, vide les valeurs déjà en base qui ne sont pas des
    nombres (ex: '' ou une plage type '12-14' saisie avant ce changement) pour éviter que le
    cast Postgres (varchar -> integer) ne fasse échouer la migration en production."""
    Bind = apps.get_model('culturelle', 'Bind')
    for b in Bind.objects.exclude(page=None):
        valeur = (b.page or '').strip()
        if not valeur.isdigit():
            Bind.objects.filter(pk=b.pk).update(page=None)


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("culturelle", "0007_laaj_question_audio_laaj_reponse_audio_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignationtere",
            name="fichier_pdf",
            field=models.FileField(
                blank=True,
                help_text="Le livre (PDF) du TERE — un seul fichier pour toute l'assignation, pas par BIND.",
                null=True,
                upload_to="majaaliss/tere_pdf/",
            ),
        ),
        # Étape intermédiaire : autoriser NULL sur le CharField existant avant le nettoyage,
        # sinon le RunPython ci-dessous ne pourrait pas vider les valeurs invalides.
        migrations.AlterField(
            model_name="bind",
            name="page",
            field=models.CharField(
                max_length=50, blank=True, null=True,
                help_text='Page(s) du TERE couverte(s) par ce BIND',
            ),
        ),
        migrations.RunPython(nettoyer_pages_non_numeriques, noop),
        migrations.AlterField(
            model_name="bind",
            name="page",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Numéro de page du TERE couverte par ce BIND",
                null=True,
            ),
        ),
    ]
