# Generated by Django 4.2.30 on 2026-09-16 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("culturelle", "0008_assignationtere_fichier_pdf_alter_bind_page"),
    ]

    operations = [
        migrations.AddField(
            model_name="bind",
            name="tarri_audio",
            field=models.FileField(
                blank=True,
                help_text="Récitation du membre (TARRI) pour ce BIND, prouvant qu'il l'a écouté/appris",
                null=True,
                upload_to="majaaliss/binds/tarri/",
            ),
        ),
        migrations.AddField(
            model_name="bind",
            name="tarri_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
