# Generated by Django 6.0.1 on 2026-02-02 09:40

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('categorie', models.CharField(choices=[('contribution', 'Contribution'), ('assiduite', 'Assiduité'), ('kamil', 'Kamil'), ('social', 'Social'), ('anciennete', 'Ancienneté'), ('special', 'Spécial')], max_length=50)),
                ('icone', models.ImageField(blank=True, null=True, upload_to='badges/')),
                ('critere', models.TextField(help_text="Critère d'obtention")),
                ('points', models.IntegerField(default=0)),
                ('est_actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Badge',
                'verbose_name_plural': 'Badges',
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('adresse', models.TextField(blank=True)),
                ('role', models.CharField(choices=[('admin', 'Administrateur'), ('membre', 'Membre'), ('jewrin', 'Jewrin')], default='membre', max_length=20)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos_membres/')),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('est_actif', models.BooleanField(default=True)),
                ('numero_wave', models.CharField(blank=True, max_length=50)),
                ('specialite', models.CharField(blank=True, max_length=100)),
                ('biographie', models.TextField(blank=True)),
                ('cotisations_payees', models.IntegerField(default=0)),
                ('chapitres_lus', models.IntegerField(default=0)),
                ('evenements_participes', models.IntegerField(default=0)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='HistoriqueConnexion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_connexion', models.DateTimeField(auto_now_add=True)),
                ('adresse_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('navigateur', models.CharField(blank=True, max_length=100)),
                ('systeme_exploitation', models.CharField(blank=True, max_length=100)),
                ('appareil', models.CharField(blank=True, max_length=100)),
                ('localisation', models.CharField(blank=True, max_length=200)),
                ('succes', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connexions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historique de Connexion',
                'verbose_name_plural': 'Historiques de Connexions',
                'ordering': ['-date_connexion'],
            },
        ),
        migrations.CreateModel(
            name='PreferencesNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notif_email_message', models.BooleanField(default=True)),
                ('notif_email_evenement', models.BooleanField(default=True)),
                ('notif_email_finance', models.BooleanField(default=True)),
                ('notif_email_kamil', models.BooleanField(default=True)),
                ('notif_push_message', models.BooleanField(default=True)),
                ('notif_push_evenement', models.BooleanField(default=True)),
                ('notif_push_finance', models.BooleanField(default=False)),
                ('notif_push_kamil', models.BooleanField(default=True)),
                ('notif_sms_urgent', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences_notif', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Préférences de Notification',
                'verbose_name_plural': 'Préférences de Notifications',
            },
        ),
        migrations.CreateModel(
            name='ProfilComplementaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biographie', models.TextField(blank=True)),
                ('profession', models.CharField(blank=True, max_length=100)),
                ('employeur', models.CharField(blank=True, max_length=100)),
                ('competences', models.TextField(blank=True)),
                ('centres_interet', models.TextField(blank=True)),
                ('facebook', models.URLField(blank=True)),
                ('twitter', models.URLField(blank=True)),
                ('linkedin', models.URLField(blank=True)),
                ('site_web', models.URLField(blank=True)),
                ('ville_residence', models.CharField(blank=True, max_length=100)),
                ('pays', models.CharField(default='Sénégal', max_length=100)),
                ('langue_preferee', models.CharField(default='fr', max_length=20)),
                ('fuseau_horaire', models.CharField(default='Africa/Dakar', max_length=50)),
                ('recevoir_newsletter', models.BooleanField(default=True)),
                ('profil_public', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil_complementaire', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil Complémentaire',
                'verbose_name_plural': 'Profils Complémentaires',
            },
        ),
        migrations.CreateModel(
            name='AttributionBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_obtention', models.DateTimeField(auto_now_add=True)),
                ('raison', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges_obtenus', to=settings.AUTH_USER_MODEL)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.badge')),
            ],
            options={
                'verbose_name': 'Attribution de Badge',
                'verbose_name_plural': 'Attributions de Badges',
                'ordering': ['-date_obtention'],
                'unique_together': {('user', 'badge')},
            },
        ),
    ]
