# Generated by Django 6.0.1 on 2026-02-02 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='photo_updated_at',
            field=models.DateTimeField(blank=True, help_text='Mis à jour à chaque changement de photo (cache bust)', null=True),
        ),
    ]
