# Generated by Django 6.0.1 on 2026-02-05 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_profession_customuser_sexe'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='numero_carte',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
