# Generated by Django 6.0.1 on 2026-02-12 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_numero_carte'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='categorie',
            field=models.CharField(choices=[('eleve', 'Élève'), ('etudiant', 'Étudiant'), ('professionnel', 'Professionnel')], default='professionnel', max_length=20),
        ),
    ]
