# Generated by Django 6.0.1 on 2026-02-18 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_customuser_categorie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrateur'), ('membre', 'Membre'), ('jewrin', 'Jewrin'), ('jewrine_conservatoire', 'Jewrin Conservatoire'), ('jewrine_culturelle', 'Jewrin Culturelle'), ('jewrine_finance', 'Jewrin Finance'), ('jewrine_sociale', 'Jewrin Sociale'), ('jewrine_communication', 'Jewrin Communication'), ('jewrine_organisation', 'Jewrin Organisation'), ('jewrine_scientifique', 'Jewrin Scientifique')], default='membre', max_length=32),
        ),
    ]
