# Generated by Django 6.0.1 on 2026-08-22 13:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_customuser_cellule_groupe_sanguin_niveaux"),
    ]

    operations = [
        migrations.CreateModel(
            name="CodeReinitialisation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=6)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("date_expiration", models.DateTimeField()),
                ("utilise", models.BooleanField(default=False)),
                ("tentatives", models.IntegerField(default=0)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="codes_reinitialisation",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Code de Réinitialisation",
                "verbose_name_plural": "Codes de Réinitialisation",
                "ordering": ["-date_creation"],
            },
        ),
    ]
