# Generated by Django 6.0.1 on 2026-08-22 14:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_codereinitialisation"),
    ]

    operations = [
        migrations.CreateModel(
            name="JournalAudit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("connexion", "Connexion"),
                            ("echec_connexion", "Échec de connexion"),
                            ("creation", "Création"),
                            ("modification", "Modification"),
                            ("suppression", "Suppression"),
                            ("validation_paiement", "Validation de paiement"),
                            ("changement_role", "Changement de rôle"),
                            ("changement_permission", "Changement de permission"),
                            ("reset_mot_de_passe", "Réinitialisation de mot de passe"),
                            ("autre", "Autre"),
                        ],
                        max_length=30,
                    ),
                ),
                ("rubrique", models.CharField(blank=True, max_length=30)),
                ("objet_repr", models.CharField(blank=True, max_length=255)),
                ("description", models.TextField(blank=True)),
                ("adresse_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("succes", models.BooleanField(default=True)),
                (
                    "utilisateur",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="journal_audit",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Entrée du Journal d'Audit",
                "verbose_name_plural": "Journal d'Audit",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="MatricePermissionRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("admin", "Administrateur"),
                            ("membre", "Membre"),
                            ("jewrin", "Jewrin"),
                            ("jewrine_conservatoire", "Jewrin Conservatoire"),
                            ("jewrine_culturelle", "Jewrin Culturelle"),
                            ("jewrine_finance", "Jewrin Finance"),
                            ("jewrine_sociale", "Jewrin Sociale"),
                            ("jewrine_communication", "Jewrin Communication"),
                            ("jewrine_organisation", "Jewrin Organisation"),
                            ("jewrine_scientifique", "Jewrin Scientifique"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "rubrique",
                    models.CharField(
                        choices=[
                            ("conservatoire", "Conservatoire"),
                            ("culturelle", "Culturelle"),
                            ("finance", "Finance"),
                            ("sociale", "Sociale"),
                            ("communication", "Communication"),
                            ("organisation", "Organisation"),
                            ("scientifique", "Scientifique"),
                            ("bibliotheque", "Bibliothèque"),
                            ("informations", "Informations"),
                            ("comptes", "Comptes / Membres"),
                        ],
                        max_length=30,
                    ),
                ),
                ("peut_voir", models.BooleanField(default=True)),
                ("peut_creer", models.BooleanField(default=False)),
                ("peut_modifier", models.BooleanField(default=False)),
                ("peut_supprimer", models.BooleanField(default=False)),
                ("peut_valider", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Matrice de Permission (par rôle)",
                "verbose_name_plural": "Matrices de Permissions (par rôle)",
                "ordering": ["role", "rubrique"],
                "unique_together": {("role", "rubrique")},
            },
        ),
        migrations.CreateModel(
            name="PermissionMembreOverride",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rubrique",
                    models.CharField(
                        choices=[
                            ("conservatoire", "Conservatoire"),
                            ("culturelle", "Culturelle"),
                            ("finance", "Finance"),
                            ("sociale", "Sociale"),
                            ("communication", "Communication"),
                            ("organisation", "Organisation"),
                            ("scientifique", "Scientifique"),
                            ("bibliotheque", "Bibliothèque"),
                            ("informations", "Informations"),
                            ("comptes", "Comptes / Membres"),
                        ],
                        max_length=30,
                    ),
                ),
                ("peut_voir", models.BooleanField(blank=True, null=True)),
                ("peut_creer", models.BooleanField(blank=True, null=True)),
                ("peut_modifier", models.BooleanField(blank=True, null=True)),
                ("peut_supprimer", models.BooleanField(blank=True, null=True)),
                ("peut_valider", models.BooleanField(blank=True, null=True)),
                ("date_modification", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="permissions_override",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Exception de Permission (par membre)",
                "verbose_name_plural": "Exceptions de Permissions (par membre)",
                "ordering": ["user", "rubrique"],
                "unique_together": {("user", "rubrique")},
            },
        ),
    ]
