# Generated by Django 6.0.1 on 2026-08-22 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_journalaudit_matricepermissionrole_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="journalaudit",
            name="user_agent",
            field=models.CharField(
                blank=True,
                help_text="En-tête User-Agent brut du navigateur/appareil",
                max_length=300,
            ),
        ),
    ]
