# Generated by Django 4.2.30 on 2026-08-24 22:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0012_seed_matrice_comptes"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="date_naissance",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="BadgeMission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "evenement",
                    models.CharField(
                        help_text="Ex : Magal 2026, Gamou, Ziarra...", max_length=200
                    ),
                ),
                (
                    "mission",
                    models.CharField(
                        help_text="Rôle dans la mission, ex : Sécurité, Accueil, Logistique",
                        max_length=200,
                    ),
                ),
                ("date_evenement", models.DateField()),
                ("description", models.TextField(blank=True)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                (
                    "cree_par",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="badges_missions_crees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "membre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="badges_missions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Badge de mission",
                "verbose_name_plural": "Badges de mission",
                "ordering": ["-date_evenement"],
            },
        ),
    ]
