# Generated by Django 4.2.30 on 2026-08-26 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0013_customuser_date_naissance_badgemission"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="date_delivrance_carte",
            field=models.DateField(
                blank=True,
                help_text="Date de délivrance de la carte de membre (distincte de l'inscription)",
                null=True,
            ),
        ),
    ]
