# Generated by Django 4.2.30 on 2026-08-28 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0014_customuser_date_delivrance_carte"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="date_expiration_carte",
            field=models.DateField(
                blank=True,
                help_text="Date de validité de la carte de membre — si vide, valable jusqu'au 31 décembre de l'année en cours",
                null=True,
            ),
        ),
    ]
