# Generated by Django 4.2.30 on 2026-09-17 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0015_customuser_date_expiration_carte"),
    ]

    operations = [
        migrations.AlterField(
            model_name="journalaudit",
            name="action",
            field=models.CharField(
                choices=[
                    ("connexion", "Connexion"),
                    ("echec_connexion", "Échec de connexion"),
                    ("creation", "Création"),
                    ("modification", "Modification"),
                    ("suppression", "Suppression"),
                    ("validation_paiement", "Validation de paiement"),
                    ("changement_role", "Changement de rôle"),
                    ("changement_permission", "Changement de permission"),
                    ("reset_mot_de_passe", "Réinitialisation de mot de passe"),
                    ("consultation", "Consultation"),
                    ("autre", "Autre"),
                ],
                max_length=30,
            ),
        ),
    ]
