# Generated by Django 6.0.1 on 2026-02-02 09:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeReunion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('couleur', models.CharField(default='#2D5F3F', max_length=7)),
                ('icone', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name': 'Type de Réunion',
                'verbose_name_plural': 'Types de Réunions',
            },
        ),
        migrations.CreateModel(
            name='RapportActivite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('periode', models.CharField(choices=[('mensuel', 'Mensuel'), ('trimestriel', 'Trimestriel'), ('semestriel', 'Semestriel'), ('annuel', 'Annuel')], max_length=20)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('contenu', models.TextField()),
                ('statistiques', models.TextField(blank=True)),
                ('points_forts', models.TextField(blank=True)),
                ('points_amelioration', models.TextField(blank=True)),
                ('recommandations', models.TextField(blank=True)),
                ('date_redaction', models.DateField()),
                ('fichier_pdf', models.FileField(blank=True, null=True, upload_to='rapports/')),
                ('redige_par', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Rapport d'Activité",
                'verbose_name_plural': "Rapports d'Activité",
                'ordering': ['-date_fin'],
            },
        ),
        migrations.CreateModel(
            name='Reunion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('ordre_du_jour', models.TextField()),
                ('date_reunion', models.DateTimeField()),
                ('duree_prevue', models.IntegerField(help_text='Durée en minutes')),
                ('lieu', models.CharField(max_length=200)),
                ('lien_visio', models.URLField(blank=True)),
                ('statut', models.CharField(choices=[('planifiee', 'Planifiée'), ('en_cours', 'En cours'), ('terminee', 'Terminée'), ('annulee', 'Annulée'), ('reportee', 'Reportée')], default='planifiee', max_length=20)),
                ('documents_preparation', models.FileField(blank=True, null=True, upload_to='reunions/documents/')),
                ('notes_preparation', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('organisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reunions_organisees', to=settings.AUTH_USER_MODEL)),
                ('participants_optionnels', models.ManyToManyField(blank=True, related_name='reunions_optionnelles', to=settings.AUTH_USER_MODEL)),
                ('participants_presents', models.ManyToManyField(blank=True, related_name='reunions_presentes', to=settings.AUTH_USER_MODEL)),
                ('participants_requis', models.ManyToManyField(blank=True, related_name='reunions_requises', to=settings.AUTH_USER_MODEL)),
                ('type_reunion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organisation.typereunion')),
            ],
            options={
                'verbose_name': 'Réunion',
                'verbose_name_plural': 'Réunions',
                'ordering': ['-date_reunion'],
            },
        ),
        migrations.CreateModel(
            name='ProcesVerbal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50, unique=True)),
                ('date_redaction', models.DateField()),
                ('presents', models.TextField()),
                ('absents', models.TextField(blank=True)),
                ('excuses', models.TextField(blank=True)),
                ('ordre_du_jour', models.TextField()),
                ('discussions', models.TextField()),
                ('decisions_prises', models.TextField()),
                ('actions_a_realiser', models.TextField(blank=True)),
                ('prochaine_reunion', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('en_validation', 'En validation'), ('valide', 'Validé'), ('publie', 'Publié')], default='brouillon', max_length=20)),
                ('fichier_pdf', models.FileField(blank=True, null=True, upload_to='pv/')),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('redige_par', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pv_rediges', to=settings.AUTH_USER_MODEL)),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pv_valides', to=settings.AUTH_USER_MODEL)),
                ('reunion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pv', to='organisation.reunion')),
            ],
            options={
                'verbose_name': 'Procès-Verbal',
                'verbose_name_plural': 'Procès-Verbaux',
                'ordering': ['-date_redaction'],
            },
        ),
        migrations.CreateModel(
            name='Decision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date_proposition', models.DateField()),
                ('statut', models.CharField(choices=[('proposee', 'Proposée'), ('en_discussion', 'En discussion'), ('approuvee', 'Approuvée'), ('rejetee', 'Rejetée'), ('en_attente', 'En attente')], default='proposee', max_length=20)),
                ('echeance', models.DateField(blank=True, null=True)),
                ('resultats', models.TextField(blank=True)),
                ('date_execution', models.DateField(blank=True, null=True)),
                ('propose_par', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions_proposees', to=settings.AUTH_USER_MODEL)),
                ('responsable_execution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decisions_responsables', to=settings.AUTH_USER_MODEL)),
                ('pv', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='organisation.procesverbal')),
                ('reunion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='organisation.reunion')),
            ],
            options={
                'verbose_name': 'Décision',
                'verbose_name_plural': 'Décisions',
                'ordering': ['-date_proposition'],
            },
        ),
        migrations.CreateModel(
            name='StructureOrganisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('ordre', models.IntegerField(default=0)),
                ('couleur', models.CharField(default='#2D5F3F', max_length=7)),
                ('membres', models.ManyToManyField(blank=True, related_name='structures_membres', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sous_structures', to='organisation.structureorganisation')),
                ('responsable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='structures_dirigees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Structure d'Organisation",
                'verbose_name_plural': "Structures d'Organisation",
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('type_vote', models.CharField(choices=[('simple', 'Majorité simple'), ('absolue', 'Majorité absolue'), ('qualifiee', 'Majorité qualifiée'), ('unanimite', 'Unanimité')], max_length=20)),
                ('date_ouverture', models.DateTimeField()),
                ('date_fermeture', models.DateTimeField()),
                ('est_anonyme', models.BooleanField(default=False)),
                ('statut', models.CharField(choices=[('ouvert', 'Ouvert'), ('ferme', 'Fermé'), ('annule', 'Annulé')], default='ouvert', max_length=20)),
                ('resultat_pour', models.IntegerField(default=0)),
                ('resultat_contre', models.IntegerField(default=0)),
                ('resultat_abstention', models.IntegerField(default=0)),
                ('decision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='organisation.decision')),
                ('lance_par', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes_lances', to=settings.AUTH_USER_MODEL)),
                ('votants_autorises', models.ManyToManyField(blank=True, related_name='votes_autorises', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vote',
                'verbose_name_plural': 'Votes',
                'ordering': ['-date_ouverture'],
            },
        ),
        migrations.CreateModel(
            name='ChoixVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choix', models.CharField(choices=[('pour', 'Pour'), ('contre', 'Contre'), ('abstention', 'Abstention')], max_length=20)),
                ('date_vote', models.DateTimeField(auto_now_add=True)),
                ('commentaire', models.TextField(blank=True)),
                ('votant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choix', to='organisation.vote')),
            ],
            options={
                'verbose_name': 'Choix de Vote',
                'verbose_name_plural': 'Choix de Votes',
                'unique_together': {('vote', 'votant')},
            },
        ),
    ]
