# Generated by Django 6.0.1

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Materiel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('categorie', models.CharField(blank=True, help_text='Ex: Sono, Micro, Bâche…', max_length=100)),
                ('quantite_totale', models.PositiveIntegerField(default=0)),
                ('quantite_disponible', models.PositiveIntegerField(default=0)),
                ('quantite_defectueuse', models.PositiveIntegerField(default=0)),
                ('lieu_stockage', models.CharField(blank=True, help_text='Ex: Daara, dépôt, salle…', max_length=200)),
                ('date_acquisition', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('derniere_mise_a_jour', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Matériel',
                'verbose_name_plural': 'Matériels',
                'ordering': ['nom'],
            },
        ),
    ]
