# Generated by Django 6.0.1 on 2026-06-22 14:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conservatoire', '0011_ensure_kourel_fks_exist'),
        ('organisation', '0002_materiel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='materiel',
            options={'ordering': ['module', 'nom'], 'verbose_name': 'Matériel', 'verbose_name_plural': 'Matériels'},
        ),
        migrations.AddField(
            model_name='materiel',
            name='module',
            field=models.CharField(choices=[('conservatoire', 'Conservatoire'), ('culturelle', 'Culturelle'), ('organisation', 'Organisation'), ('generale', 'Générale')], default='generale', max_length=50),
        ),
        migrations.CreateModel(
            name='EvenementOrganise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('type_evenement', models.CharField(choices=[('magal', 'Magal'), ('gamou', 'Gamou'), ('ziarra', 'Ziarra'), ('conference', 'Conférence'), ('autre', 'Autre')], default='autre', max_length=50)),
                ('annee', models.IntegerField(default=2025)),
                ('description', models.TextField(blank=True)),
                ('lieu', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evenements_organises', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Événement Organisé',
                'verbose_name_plural': 'Événements Organisés',
                'ordering': ['-annee', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='JourneeEvenement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Ex: 17 Safar', max_length=100)),
                ('date', models.DateField(blank=True, null=True)),
                ('ordre', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('evenement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journees', to='organisation.evenementorganise')),
            ],
            options={
                'verbose_name': "Journée d'Événement",
                'verbose_name_plural': "Journées d'Événement",
                'ordering': ['ordre', 'date', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='KourelInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordre', models.IntegerField(default=0)),
                ('heure_debut', models.TimeField(blank=True, null=True)),
                ('duree', models.IntegerField(default=60, help_text='Durée en minutes')),
                ('programme', models.TextField(blank=True, help_text='Programme de prestation')),
                ('appreciation', models.TextField(blank=True, help_text='Appréciation conservatoire')),
                ('note', models.DecimalField(blank=True, decimal_places=1, help_text='Note /20', max_digits=4, null=True)),
                ('journee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kourels_invites', to='organisation.journeeevenement')),
                ('kourel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='conservatoire.kourel')),
            ],
            options={
                'verbose_name': 'Kourel Invité',
                'verbose_name_plural': 'Kourels Invités',
                'ordering': ['ordre', 'heure_debut'],
            },
        ),
    ]
