# Generated by Django 4.2.29 on 2026-06-22 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conservatoire', '0011_ensure_kourel_fks_exist'),
        ('organisation', '0003_alter_materiel_options_materiel_module_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kourelinvite',
            name='nom_kourel',
            field=models.CharField(blank=True, help_text='Nom du kourel invité (si externe)', max_length=200),
        ),
        migrations.AddField(
            model_name='kourelinvite',
            name='statut_invitation',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('valide', 'Validé'), ('desiste', 'Désisté')], default='en_attente', max_length=20),
        ),
        migrations.AlterField(
            model_name='kourelinvite',
            name='kourel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitations', to='conservatoire.kourel'),
        ),
    ]
