# Generated by Django 6.0.1 on 2026-02-02 09:40

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_complet', models.CharField(max_length=200)),
                ('categorie', models.CharField(choices=[('famille', 'Famille'), ('orphelin', 'Orphelin'), ('veuve', 'Veuve'), ('malade', 'Malade'), ('etudiant', 'Étudiant'), ('autre', 'Autre')], max_length=50)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('telephone', models.CharField(max_length=20)),
                ('adresse', models.TextField()),
                ('situation', models.TextField(help_text='Description de la situation')),
                ('nombre_personnes_charge', models.IntegerField(default=0)),
                ('revenu_mensuel', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('besoins', models.TextField()),
                ('date_enregistrement', models.DateTimeField(auto_now_add=True)),
                ('est_actif', models.BooleanField(default=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='beneficiaires/')),
                ('documents', models.FileField(blank=True, null=True, upload_to='beneficiaires/docs/')),
                ('referent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='beneficiaires_suivis', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bénéficiaire',
                'verbose_name_plural': 'Bénéficiaires',
                'ordering': ['nom_complet'],
            },
        ),
        migrations.CreateModel(
            name='ParticipationProjet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('benevole', 'Bénévole'), ('coordinateur', 'Coordinateur'), ('expert', 'Expert')], default='benevole', max_length=20)),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('heures_contribution', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('commentaire', models.TextField(blank=True)),
                ('membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Participation Projet',
                'verbose_name_plural': 'Participations Projets',
            },
        ),
        migrations.CreateModel(
            name='ProjetEntraide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('categorie', models.CharField(choices=[('education', 'Éducation'), ('sante', 'Santé'), ('alimentation', 'Alimentation'), ('logement', 'Logement'), ('emploi', 'Emploi'), ('urgence', 'Urgence'), ('autre', 'Autre')], max_length=50)),
                ('objectifs', models.TextField()),
                ('budget_previsionnel', models.DecimalField(decimal_places=2, max_digits=12)),
                ('budget_utilise', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('planifie', 'Planifié'), ('en_cours', 'En cours'), ('termine', 'Terminé'), ('annule', 'Annulé')], default='planifie', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='projets_sociaux/')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('benevoles', models.ManyToManyField(blank=True, related_name='projets_benevole', through='sociale.ParticipationProjet', to=settings.AUTH_USER_MODEL)),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projets_responsable', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Projet d'Entraide",
                'verbose_name_plural': "Projets d'Entraide",
                'ordering': ['-date_creation'],
            },
        ),
        migrations.AddField(
            model_name='participationprojet',
            name='projet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sociale.projetentraide'),
        ),
        migrations.CreateModel(
            name='AideAccordee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_aide', models.CharField(choices=[('financiere', 'Aide Financière'), ('materielle', 'Aide Matérielle'), ('alimentaire', 'Aide Alimentaire'), ('medicale', 'Aide Médicale'), ('scolaire', 'Aide Scolaire'), ('autre', 'Autre')], max_length=50)),
                ('description', models.TextField()),
                ('montant', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('date_aide', models.DateField()),
                ('justificatif', models.FileField(blank=True, null=True, upload_to='aides/justificatifs/')),
                ('notes', models.TextField(blank=True)),
                ('accorde_par', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('beneficiaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aides_recues', to='sociale.beneficiaire')),
                ('projet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sociale.projetentraide')),
            ],
            options={
                'verbose_name': 'Aide Accordée',
                'verbose_name_plural': 'Aides Accordées',
                'ordering': ['-date_aide'],
            },
        ),
        migrations.CreateModel(
            name='ActionSociale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('type_action', models.CharField(choices=[('distribution', 'Distribution'), ('visite', 'Visite'), ('formation', 'Formation'), ('sensibilisation', 'Sensibilisation'), ('autre', 'Autre')], max_length=50)),
                ('description', models.TextField()),
                ('date_action', models.DateTimeField()),
                ('lieu', models.CharField(max_length=200)),
                ('nombre_beneficiaires', models.IntegerField(default=0)),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('rapport', models.TextField(blank=True)),
                ('photos', models.ImageField(blank=True, null=True, upload_to='actions_sociales/')),
                ('organisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions_organisees', to=settings.AUTH_USER_MODEL)),
                ('participants', models.ManyToManyField(blank=True, related_name='actions_participees', to=settings.AUTH_USER_MODEL)),
                ('projet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions', to='sociale.projetentraide')),
            ],
            options={
                'verbose_name': 'Action Sociale',
                'verbose_name_plural': 'Actions Sociales',
                'ordering': ['-date_action'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='participationprojet',
            unique_together={('projet', 'membre')},
        ),
    ]
