# Generated by Django 6.0.1 on 2026-02-03 11:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sociale', '0002_contributionsociale'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='projetentraide',
            name='lieu',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='projetentraide',
            name='membre_concerne',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projets_sociaux_concerne', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projetentraide',
            name='objectif_social',
            field=models.TextField(blank=True, help_text='Objectif social si pas de membre concerné (ex: Magal, Gamou)'),
        ),
    ]
