# Generated by Django 6.0.1 on 2026-02-02 09:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlbumPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('date_evenement', models.DateField()),
                ('couverture', models.ImageField(blank=True, null=True, upload_to='conservatoire/albums/couvertures/')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('est_public', models.BooleanField(default=True)),
                ('cree_par', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Album Photo',
                'verbose_name_plural': 'Albums Photos',
                'ordering': ['-date_evenement'],
            },
        ),
        migrations.CreateModel(
            name='ArchiveHistorique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('type_archive', models.CharField(choices=[('evenement', 'Événement Historique'), ('personnalite', 'Personnalité'), ('document', 'Document Ancien'), ('photo', 'Photo Ancienne'), ('temoignage', 'Témoignage'), ('autre', 'Autre')], max_length=50)),
                ('date_evenement', models.DateField(help_text="Date de l'événement/document")),
                ('annee', models.IntegerField()),
                ('description', models.TextField()),
                ('contexte_historique', models.TextField(blank=True)),
                ('fichier', models.FileField(blank=True, null=True, upload_to='conservatoire/archives/')),
                ('image', models.ImageField(blank=True, null=True, upload_to='conservatoire/archives/images/')),
                ('source', models.CharField(blank=True, max_length=200)),
                ('date_archivage', models.DateTimeField(auto_now_add=True)),
                ('archiviste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Archive Historique',
                'verbose_name_plural': 'Archives Historiques',
                'ordering': ['annee', 'date_evenement'],
            },
        ),
        migrations.CreateModel(
            name='CategorieDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('icone', models.CharField(blank=True, max_length=50)),
                ('ordre', models.IntegerField(default=0)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sous_categories', to='conservatoire.categoriedocument')),
            ],
            options={
                'verbose_name': 'Catégorie de Document',
                'verbose_name_plural': 'Catégories de Documents',
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='DocumentNumerique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('auteur', models.CharField(max_length=200)),
                ('type_document', models.CharField(choices=[('livre', 'Livre'), ('article', 'Article'), ('these', 'Thèse'), ('memoire', 'Mémoire'), ('rapport', 'Rapport'), ('guide', 'Guide'), ('autre', 'Autre')], max_length=50)),
                ('description', models.TextField()),
                ('fichier', models.FileField(upload_to='conservatoire/documents/')),
                ('couverture', models.ImageField(blank=True, null=True, upload_to='conservatoire/couvertures/')),
                ('nombre_pages', models.IntegerField(blank=True, null=True)),
                ('annee_publication', models.IntegerField(blank=True, null=True)),
                ('editeur', models.CharField(blank=True, max_length=200)),
                ('isbn', models.CharField(blank=True, max_length=50)),
                ('langue', models.CharField(default='Français', max_length=50)),
                ('tags', models.CharField(blank=True, max_length=200)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('telechargements', models.IntegerField(default=0)),
                ('vues', models.IntegerField(default=0)),
                ('categorie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='conservatoire.categoriedocument')),
                ('telecharge_par', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document Numérique',
                'verbose_name_plural': 'Documents Numériques',
                'ordering': ['-date_ajout'],
            },
        ),
        migrations.CreateModel(
            name='MediaAudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('categorie', models.CharField(choices=[('wird', 'Wird'), ('khassida', 'Khassida'), ('conference', 'Conférence'), ('cours', 'Cours'), ('sermon', 'Sermon'), ('recitation', 'Récitation Coran'), ('autre', 'Autre')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('orateur', models.CharField(blank=True, max_length=200)),
                ('fichier_audio', models.FileField(upload_to='conservatoire/audio/')),
                ('duree', models.IntegerField(blank=True, help_text='Durée en secondes', null=True)),
                ('date_enregistrement', models.DateField(blank=True, null=True)),
                ('lieu_enregistrement', models.CharField(blank=True, max_length=200)),
                ('qualite', models.CharField(blank=True, max_length=50)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('ecoutes', models.IntegerField(default=0)),
                ('tags', models.CharField(blank=True, max_length=200)),
                ('upload_par', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Média Audio',
                'verbose_name_plural': 'Médias Audio',
                'ordering': ['-date_ajout'],
            },
        ),
        migrations.CreateModel(
            name='MediaVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('categorie', models.CharField(choices=[('evenement', 'Événement'), ('cours', 'Cours'), ('conference', 'Conférence'), ('ceremonie', 'Cérémonie'), ('documentaire', 'Documentaire'), ('interview', 'Interview'), ('autre', 'Autre')], max_length=50)),
                ('description', models.TextField()),
                ('intervenant', models.CharField(blank=True, max_length=200)),
                ('fichier_video', models.FileField(upload_to='conservatoire/videos/')),
                ('miniature', models.ImageField(blank=True, null=True, upload_to='conservatoire/miniatures/')),
                ('duree', models.IntegerField(blank=True, help_text='Durée en secondes', null=True)),
                ('date_tournage', models.DateField(blank=True, null=True)),
                ('lieu_tournage', models.CharField(blank=True, max_length=200)),
                ('resolution', models.CharField(blank=True, max_length=50)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('vues', models.IntegerField(default=0)),
                ('tags', models.CharField(blank=True, max_length=200)),
                ('upload_par', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Média Vidéo',
                'verbose_name_plural': 'Médias Vidéo',
                'ordering': ['-date_ajout'],
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('fichier', models.ImageField(upload_to='conservatoire/photos/')),
                ('date_prise', models.DateField(blank=True, null=True)),
                ('lieu', models.CharField(blank=True, max_length=200)),
                ('date_upload', models.DateTimeField(auto_now_add=True)),
                ('ordre', models.IntegerField(default=0)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='conservatoire.albumphoto')),
                ('photographe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos_prises', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Photo',
                'verbose_name_plural': 'Photos',
                'ordering': ['album', 'ordre'],
            },
        ),
    ]
