# Generated by Django 6.0.1 on 2026-02-02 23:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conservatoire', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgrammeConservatoire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('cree_par', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Programme Conservatoire',
                'verbose_name_plural': 'Programmes Conservatoire',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='Kourel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('ordre', models.IntegerField(default=0)),
                ('membres', models.ManyToManyField(blank=True, related_name='kourels', to=settings.AUTH_USER_MODEL)),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kourels', to='conservatoire.programmeconservatoire')),
            ],
            options={
                'verbose_name': 'Kourel',
                'verbose_name_plural': 'Kourels',
                'ordering': ['programme', 'ordre', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='SeanceConservatoire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_seance', models.CharField(choices=[('repetition', 'Répétition'), ('prestation', 'Prestation')], default='repetition', max_length=20)),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('date_heure', models.DateTimeField()),
                ('lieu', models.CharField(blank=True, max_length=200)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('cree_par', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('kourel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seances', to='conservatoire.kourel')),
            ],
            options={
                'verbose_name': 'Séance Conservatoire',
                'verbose_name_plural': 'Séances Conservatoire',
                'ordering': ['-date_heure'],
            },
        ),
    ]
