# Generated by Django 6.0.1 on 2026-02-02 23:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conservatoire', '0002_add_programme_kourel_seance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='kourel',
            name='maitre_de_coeur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kourels_diriges', to=settings.AUTH_USER_MODEL),
        ),
    ]
