# Generated by Django 6.0.1 on 2026-02-02 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conservatoire', '0003_add_maitre_de_coeur'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kourel',
            name='programme',
        ),
        migrations.AlterModelOptions(
            name='kourel',
            options={'ordering': ['ordre', 'nom'], 'verbose_name': 'Kourel', 'verbose_name_plural': 'Kourels'},
        ),
        migrations.DeleteModel(
            name='ProgrammeConservatoire',
        ),
    ]
