# Generated by Django 6.0.1

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('conservatoire', '0004_kourel_independent_programme'),
    ]

    operations = [
        migrations.AddField(
            model_name='seanceconservatoire',
            name='heure_fin',
            field=models.TimeField(blank=True, help_text='Heure de fin de la répétition', null=True),
        ),
        migrations.AddField(
            model_name='seanceconservatoire',
            name='nom_khassida',
            field=models.CharField(blank=True, help_text='Nom de la khassida travaillée', max_length=200),
        ),
        migrations.AddField(
            model_name='seanceconservatoire',
            name='khassida_portion',
            field=models.CharField(blank=True, help_text='Portion ou partie de la khassida', max_length=200),
        ),
        migrations.AddField(
            model_name='seanceconservatoire',
            name='date_khassida',
            field=models.DateField(blank=True, help_text='Date de la khassida', null=True),
        ),
        migrations.AlterField(
            model_name='seanceconservatoire',
            name='date_heure',
            field=models.DateTimeField(help_text='Date et heure de début'),
        ),
        migrations.CreateModel(
            name='PresenceSeance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('present', 'Présent'), ('absent_non_justifie', 'Absent non justifié'), ('absent_justifie', 'Absent justifié')], default='present', max_length=30)),
                ('remarque', models.TextField(blank=True, help_text='Justification ou remarque si absent justifié')),
                ('membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presences_seances', to=settings.AUTH_USER_MODEL)),
                ('seance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presences', to='conservatoire.seanceconservatoire')),
            ],
            options={
                'verbose_name': 'Présence à une séance',
                'verbose_name_plural': 'Présences aux séances',
                'ordering': ['seance', 'membre'],
                'unique_together': {('seance', 'membre')},
            },
        ),
    ]
