# Generated by Django 6.0.1

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conservatoire', '0005_seance_presences'),
    ]

    operations = [
        migrations.CreateModel(
            name='KhassidaRepetee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_khassida', models.CharField(help_text='Nom de la khassida', max_length=200)),
                ('khassida_portion', models.CharField(blank=True, help_text='Portion ou partie travaillée', max_length=200)),
                ('dathie', models.CharField(help_text='Dathie - ex : Serigne Massamba, Serigne Mahib', max_length=200)),
                ('ordre', models.IntegerField(default=0)),
                ('seance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='khassidas', to='conservatoire.seanceconservatoire')),
            ],
            options={
                'verbose_name': 'Khassida répétée',
                'verbose_name_plural': 'Khassidas répétées',
                'ordering': ['seance', 'ordre', 'id'],
            },
        ),
        migrations.RemoveField(model_name='seanceconservatoire', name='nom_khassida'),
        migrations.RemoveField(model_name='seanceconservatoire', name='khassida_portion'),
        migrations.RemoveField(model_name='seanceconservatoire', name='date_khassida'),
    ]
