# Generated by Django 4.2.29 on 2026-06-21 00:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('conservatoire', '0009_alter_archivehistorique_lien_charfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='kourel',
            name='jewrine',
            field=models.ForeignKey(blank=True, help_text='Jewrine responsable de ce kourel', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kourels_jewrine', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='kourel',
            name='maitre_de_coeur_2',
            field=models.ForeignKey(blank=True, help_text='2ème Maître de cœur', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kourels_diriges_2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='kourel',
            name='responsable',
            field=models.ForeignKey(blank=True, help_text='Responsable principal du kourel', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kourels_responsable', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='kourel',
            name='maitre_de_coeur',
            field=models.ForeignKey(blank=True, help_text='1er Maître de cœur', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kourels_diriges', to=settings.AUTH_USER_MODEL),
        ),
    ]
