# Generated by Django 4.2.30 on 2026-08-23 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conservatoire", "0011_ensure_kourel_fks_exist"),
    ]

    operations = [
        migrations.AddField(
            model_name="khassidarepetee",
            name="melodie",
            field=models.CharField(
                blank=True,
                help_text="Mélodie à utiliser pour cette khassida",
                max_length=200,
            ),
        ),
    ]
