# Generated by Django 4.2.29 on 2026-08-23 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("conservatoire", "0012_khassidarepetee_melodie"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="khassidarepetee",
            name="melodie",
        ),
    ]
