# Generated by Django 4.2.30 on 2026-09-30 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conservatoire", "0013_remove_khassidarepetee_melodie"),
    ]

    operations = [
        migrations.AlterField(
            model_name="presenceseance",
            name="remarque",
            field=models.TextField(
                blank=True,
                help_text="Justification (facultative) si absent justifié, ou remarque générale",
            ),
        ),
        migrations.AlterField(
            model_name="presenceseance",
            name="statut",
            field=models.CharField(
                choices=[
                    ("present", "Présent"),
                    ("present_retard", "Présent (retard)"),
                    ("present_hors_kourel", "Présent (hors kourel)"),
                    ("absent_non_justifie", "Absent non justifié"),
                    ("absent_justifie", "Absent justifié"),
                ],
                default="present",
                max_length=30,
            ),
        ),
    ]
