# Generated by Django 4.2.30 on 2026-10-01 00:24

from django.db import migrations, models


def migrer_hors_kourel_vers_invite(apps, schema_editor):
    """Le statut 'present_hors_kourel' signifiait jusqu'ici "invité d'un autre kourel" —
    il a désormais un sens différent ("membre du kourel présent mais n'ayant pas presté").
    Les lignes existantes créées pour un membre qui n'appartient PAS au kourel de la séance
    sont donc de VRAIS invités externes sous l'ancien sens : on les bascule vers le nouveau
    statut dédié 'present_invite' pour préserver leur sens et leurs statistiques."""
    PresenceSeance = apps.get_model('conservatoire', 'PresenceSeance')
    for p in PresenceSeance.objects.filter(statut='present_hors_kourel').select_related('seance__kourel'):
        kourel = p.seance.kourel if p.seance_id else None
        if kourel is None:
            continue
        est_membre_du_kourel = kourel.membres.filter(pk=p.membre_id).exists()
        if not est_membre_du_kourel:
            p.statut = 'present_invite'
            p.save(update_fields=['statut'])


def inverser(apps, schema_editor):
    # Pas de retour en arrière fiable (on perdrait la distinction) : no-op volontaire.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("conservatoire", "0014_alter_presenceseance_remarque_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="presenceseance",
            name="statut",
            field=models.CharField(
                choices=[
                    ("present", "Présent"),
                    ("present_retard", "Présent (retard)"),
                    ("present_hors_kourel", "Présent (hors kourel)"),
                    ("present_invite", "Présent (invité d'un autre kourel)"),
                    ("absent_non_justifie", "Absent non justifié"),
                    ("absent_justifie", "Absent justifié"),
                ],
                default="present",
                max_length=30,
            ),
        ),
        migrations.RunPython(migrer_hors_kourel_vers_invite, inverser),
    ]
