# Generated by Django

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LivreNumerique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('pdf', models.FileField(upload_to='bibliotheque/livres/')),
                ('categorie', models.CharField(choices=[('alquran', 'ALQURAN'), ('qassida', 'QASSIDA')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('ordre', models.IntegerField(default=0, help_text="Ordre d'affichage dans la catégorie")),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('telechargements', models.IntegerField(default=0)),
                ('vues', models.IntegerField(default=0)),
                ('ajoute_par', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livres_ajoutes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Livre numérique',
                'verbose_name_plural': 'Livres numériques',
                'ordering': ['categorie', 'ordre', 'nom'],
            },
        ),
    ]
