# Generated by Django 6.0.1 on 2026-02-21 08:29

import apps.bibliotheque.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotheque', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livrenumerique',
            name='pdf',
            field=models.FileField(upload_to=apps.bibliotheque.models.chemin_pdf_bibliotheque),
        ),
    ]
